import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, KeyRound, ShieldCheck, Webhook } from "lucide-react";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://elpino.chat";
export const metadata: Metadata = { title: "API & Webhooks", description: "Build with the Elpino API and receive real-time customer support events.", alternates: { canonical: `${SITE_URL}/docs/api-webhooks` } };
const endpoints = [["GET", "/v1/conversations", "List conversations"], ["POST", "/v1/conversations/:id/messages", "Send a message"], ["GET", "/v1/contacts", "List contacts"], ["POST", "/v1/knowledge", "Add trusted knowledge"]] as const;
const events = [["conversation.created", "A visitor or teammate starts a conversation."], ["conversation.resolved", "A conversation is marked resolved."], ["message.created", "A new message arrives."], ["contact.updated", "Contact details change."], ["knowledge.indexed", "Knowledge is ready to use."]] as const;
function Code({ title, children }: { title: string; children: string }) { return <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#141b22] shadow-[0_25px_60px_rgba(0,0,0,0.24)]"><div className="flex items-center justify-between border-b border-white/10 px-5 py-3"><span className="font-mono text-xs text-white/60">{title}</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#d9bef4]">Elpino</span></div><pre className="overflow-x-auto p-5 text-[13px] leading-7 text-[#dce6f0]"><code>{children}</code></pre></div>; }
export default function ApiWebhooksPage() { return <main className="min-h-screen bg-[#f7f7f5] font-[family-name:var(--font-rethink-sans)] text-[#233d4d]">
  <header className="border-b border-[#233d4d]/15 px-5 sm:px-8"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm font-semibold"><Image src="/icon.png" alt="" width={32} height={32} className="size-8 rounded-lg" />elpino <span className="font-normal text-[#66747c]">/ Developer docs</span></Link><Link href="/dashboard" className="rounded-full bg-[#233d4d] px-4 py-2 text-xs font-semibold text-white">Dashboard</Link></div></header>
  <section className="relative overflow-hidden bg-[#233d4d] px-5 py-16 text-white sm:px-8 sm:py-24"><div aria-hidden="true" className="absolute -right-24 -top-24 size-[30rem] rounded-full bg-[#8d65b5]/40 blur-3xl" /><div className="relative mx-auto grid max-w-[1440px] items-center gap-8 lg:grid-cols-[1fr_0.7fr]"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#d9bef4]">Elpino developers</p><h1 className="mt-5 max-w-4xl text-[clamp(3.25rem,7vw,7.5rem)] font-medium leading-[0.86] tracking-[-0.075em]">Build support that stays in sync.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">Use the API to extend your workspace and webhooks to react to every important support moment, in real time.</p><a href="#quickstart" className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-6 text-sm font-semibold text-[#233d4d]">Start building <ArrowRight size={16} /></a></div><Image src="/images/help-center-sloth.png" alt="A sloth organizing customer support knowledge" width={1024} height={1536} priority className="mx-auto h-[330px] w-auto object-contain sm:h-[390px]" /></div></section>
  <div className="mx-auto max-w-[1120px] px-5 py-14 sm:px-10"><section id="quickstart" className="border-b border-[#233d4d]/15 pb-14"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#6c48a0]">Quickstart</p><div className="mt-4 grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><h2 className="text-4xl font-medium leading-[0.96] tracking-[-0.055em]">Your first API call in under a minute.</h2><p className="mt-5 text-base leading-7 text-[#5d6872]">Create a workspace API key in Settings, then call any Elpino endpoint from your server.</p><p className="mt-6 flex items-center gap-3 text-sm font-semibold"><span className="flex size-8 items-center justify-center rounded-full bg-[#d9bef4]"><Check size={16} /></span>api.elpino.chat/v1</p></div><Code title="cURL">{'curl https://api.elpino.chat/v1/conversations -H "Authorization: Bearer YOUR_API_KEY"'}</Code></div></section>
  <section id="authentication" className="grid gap-7 border-b border-[#233d4d]/15 py-14 sm:grid-cols-[auto_1fr]"><span className="flex size-13 items-center justify-center rounded-2xl bg-[#d9bef4]"><KeyRound size={22} /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#6c48a0]">Authentication</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.045em]">Keys belong on your server.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[#5d6872]">API keys are workspace-scoped. Send yours as a Bearer token, never expose it in browser code, and rotate it whenever you need to.</p></div></section>
  <section id="endpoints" className="border-b border-[#233d4d]/15 py-14"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#6c48a0]">API reference</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.045em]">The essentials, without the ceremony.</h2><div className="mt-7 divide-y divide-[#233d4d]/15 border-y border-[#233d4d]/15">{endpoints.map(([method, path, description]) => <div key={path} className="grid gap-2 py-4 sm:grid-cols-[74px_minmax(190px,0.85fr)_1.15fr] sm:items-center"><span className={`w-fit rounded-full px-2.5 py-1 font-mono text-[11px] font-bold ${method === "GET" ? "bg-[#d8f0e5] text-[#176143]" : "bg-[#dce7ff] text-[#243d88]"}`}>{method}</span><code className="font-mono text-sm">{path}</code><span className="text-sm text-[#5d6872]">{description}</span></div>)}</div></section>
  <section id="webhooks" className="grid gap-8 border-b border-[#233d4d]/15 py-14 lg:grid-cols-[0.78fr_1.22fr]"><div><span className="flex size-13 items-center justify-center rounded-2xl bg-[#18c983]"><Webhook size={23} /></span><p className="mt-6 text-xs font-bold uppercase tracking-[0.14em] text-[#28745a]">Webhooks</p><h2 className="mt-3 text-4xl font-medium leading-[0.96] tracking-[-0.055em]">Let Elpino tell you when something changes.</h2><p className="mt-5 text-base leading-7 text-[#5d6872]">Register an HTTPS endpoint in Settings → Webhooks. We’ll POST a signed payload whenever a selected event occurs.</p></div><Code title="JSON payload">{'{\n  "event": "message.created",\n  "workspace_id": "ws_elpino01",\n  "data": { "conversation_id": "conv_abc123" }\n}'}</Code></section>
  <section id="events" className="border-b border-[#233d4d]/15 py-14"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#6c48a0]">Event reference</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.045em]">Subscribe only to the signals you need.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{events.map(([event, description]) => <article key={event} className="rounded-2xl border border-[#233d4d]/15 bg-white p-5"><code className="font-mono text-sm font-semibold text-[#6c48a0]">{event}</code><p className="mt-3 text-sm leading-6 text-[#5d6872]">{description}</p></article>)}</div></section>
  <section className="py-14"><div className="rounded-3xl bg-[#233d4d] p-7 text-white sm:p-10"><ShieldCheck size={28} className="text-[#d9bef4]" /><h2 className="mt-8 text-3xl font-medium tracking-[-0.045em]">Verify every delivery.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-white/65">Each webhook includes an <code className="rounded bg-white/10 px-1.5 py-0.5 font-mono text-sm">X-Elpino-Signature</code> HMAC-SHA256 signature. Validate it against your webhook secret. Failed deliveries are retried up to three times.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#d9bef4]">Need integration help? Talk to us <ArrowRight size={15} /></Link></div></section></div>
</main>; }
