"use client";

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, Check, CreditCard, FileText, KanbanSquare, KeyRound, LockKeyhole, MessageCircle, Plug, Plus, ShieldCheck, Sparkles } from 'lucide-react';
import { categories } from '../faq/faq-categories';

const wrap = 'mx-auto max-w-[1500px] px-5 sm:px-8 lg:px-20';
const button = 'inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-[#191f19] px-6 text-sm font-medium text-white transition hover:bg-[#343c34] focus-visible:outline-2 focus-visible:outline-offset-4';
const heading = 'text-3xl font-medium leading-[1.08] tracking-[-0.045em] sm:text-4xl lg:text-5xl';
const integrationFaqs = categories.find(category => category.name === 'Integrations')?.items ?? [];
const integrations = [
  { id: 'stripe', name: 'Stripe', category: 'Payments', color: '#635bff', letter: 'S', tagline: 'Billing answers, backed by the order.', description: "Let Elpino look up a customer's order in Stripe before answering a billing question, matched to the email on their record.", points: ['Read-only order lookups', 'Matched to customer email', 'Context for billing conversations'] },
  { id: 'razorpay', name: 'Razorpay', category: 'Payments', color: '#2465dc', letter: 'R', tagline: 'Your payment context. Right there.', description: 'Connect Razorpay to give Elpino real order information when customers need help with a payment or billing question.', points: ['Read-only payment access', 'Customer email matching', 'No changes to payment records'] },
  { id: 'trello', name: 'Trello', category: 'Ticketing', color: '#0079bf', letter: 'T', tagline: 'Turn a handoff into a next step.', description: "Send escalations that need tracked follow-up to Trello, with the conversation's context attached to a card your team can work on.", points: ['Cards for tracked follow-ups', 'Conversation context attached', 'Work stays visible to your team'] },
] as const;

function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={false} whileInView={reduced ? undefined : { opacity: [0.4, 1], y: [18, 0] }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.6, ease: 'easeOut' }}>{children}</motion.div>;
}

function ProviderMark({ provider }: { provider: typeof integrations[number] }) {
  return <span aria-hidden="true" className="flex size-14 shrink-0 items-center justify-center rounded-2xl text-3xl font-bold text-white" style={{ backgroundColor: provider.color }}>{provider.id === 'trello' ? <KanbanSquare size={28} /> : provider.letter}</span>;
}

function Directory() {
  const [filter, setFilter] = useState('All integrations');
  const filtered = integrations.filter(item => filter === 'All integrations' || item.category === filter);
  return <section className="bg-[linear-gradient(180deg,#DDEFEA_0%,#EBE5FA_65%,#FFFFFF_100%)] pb-16 pt-16 sm:pt-20"><div className={wrap}>
    <Reveal className="grid gap-8 lg:grid-cols-[1.45fr_1fr] lg:items-end"><div><span className="mb-6 inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/80 px-3 py-1.5 text-[11px]"><Plug size={13} /> Connected to the way you work</span><h1 className="text-[clamp(2.6rem,4.5vw,4.7rem)] font-medium leading-[1.02] tracking-[-0.055em]">Your tools.<br />More helpful answers.</h1><p className="mt-5 max-w-[46ch] text-base leading-7 text-[#5e6866]">Bring payment context and tracked follow-ups into your customer conversations. A few useful connections. A little less back-and-forth.</p></div><div className="flex flex-col items-start gap-4 lg:items-end"><Link href="/dashboard/connect" className={button}>Connect your tools <ArrowUpRight size={17} /></Link><span className="text-xs text-[#717779]">Already have a workspace? Sign in to connect.</span></div></Reveal>
    <div id="integration-directory" className="mb-7 mt-12 flex scroll-mt-36 flex-col justify-between gap-5 sm:flex-row sm:items-center"><span className="inline-flex w-fit items-center gap-2 text-sm"><Plug size={17} /> Explore integrations <span className="text-[#72767d]">({integrations.length})</span></span><div role="group" aria-label="Filter integrations" className="inline-flex w-fit flex-wrap rounded-full border border-black/5 bg-[#f8f9f9] p-1">{['All integrations', 'Payments', 'Ticketing'].map(category => <button key={category} type="button" aria-pressed={filter === category} aria-controls="integration-results" onClick={() => setFilter(category)} className={`min-h-10 rounded-full px-4 text-xs transition focus-visible:outline-2 focus-visible:outline-offset-2 sm:text-sm ${filter === category ? 'bg-white text-black shadow-sm' : 'text-[#676d74] hover:text-black'}`}>{category}</button>)}</div></div>
    <p role="status" className="sr-only">Showing {filtered.length} integrations</p>
    <div id="integration-results" className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(provider => <article key={provider.id} className="flex flex-col overflow-hidden rounded-2xl border border-white bg-white p-6 shadow-[0_16px_35px_-15px_rgba(30,28,60,0.18)] sm:p-7"><div className="mb-6 flex items-start justify-between"><ProviderMark provider={provider} /><span className="inline-flex items-center gap-1.5 rounded-full bg-[#ecf6ef] px-2.5 py-1 text-[10px] text-[#37744f]"><span className="size-1 rounded-full bg-[#4a9d65]" /> Available</span></div><p className="text-[10px] uppercase tracking-wider text-[#7a6a98]">{provider.category}</p><h2 className="mt-2 text-3xl font-medium tracking-[-0.04em]">{provider.name}</h2><p className="mt-4 text-base font-medium leading-6">{provider.tagline}</p><p className="mb-6 mt-3 text-sm leading-7 text-[#737982]">{provider.description}</p><ul className="mt-auto space-y-3 border-t border-black/10 pt-5">{provider.points.map(point => <li key={point} className="flex items-start gap-2.5 text-xs leading-6"><Check size={15} className="mt-1 shrink-0 text-[#00a883]" />{point}</li>)}</ul><Link href="/dashboard/connect" aria-label={`Set up ${provider.name} in your workspace`} className={`${button} mt-7 w-full`}>Set up {provider.name} <ArrowUpRight size={15} /></Link></article>)}</div>
    <p className="mt-7 text-xs leading-6 text-[#747a81]">Looking for something else? <Link href="/contact" className="text-[#3f3b4b] underline underline-offset-4">Tell us which integration you need.</Link></p>
  </div></section>;
}

const workflows = [
  { label: 'Payment questions', icon: CreditCard, title: 'A real order.\nA better answer.', text: 'When a customer asks about billing, Elpino can look up the order through your payment connection before it replies.', source: 'Stripe or Razorpay', steps: ['Customer asks a billing question', 'Order matched to their email', 'Payment information checked', 'Elpino answers with context'], question: 'Can you check the payment for my order?', result: 'Order information is available for the reply.', badge: 'Read-only lookup', resultIcon: ShieldCheck },
  { label: 'Tracked follow-ups', icon: KanbanSquare, title: 'The conversation ends.\nThe follow-up doesn’t.', text: 'When an escalation needs tracked work, Trello gives your team a card with the customer conversation attached.', source: 'Trello', steps: ['Customer needs a teammate', 'Follow-up work is identified', 'Trello card created with context', 'Your team tracks the next step'], question: 'I need someone to investigate this issue.', result: 'A follow-up card keeps the work visible.', badge: 'Conversation context included', resultIcon: FileText },
];

function Workflow() {
  const [active, setActive] = useState(0);
  const reduced = useReducedMotion();
  const example = workflows[active];
  return <section className="bg-black py-20 text-white sm:py-24"><div className={wrap}><Reveal className="mb-10 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="mb-4 text-xs uppercase tracking-wider text-[#c6a5ed]">Connections with a purpose</p><h2 className={heading}>Less looking things up.<br />More moving things along.</h2></div><div role="group" aria-label="Choose a workflow" className="flex w-fit flex-wrap gap-2">{workflows.map((item, i) => <button key={item.label} type="button" aria-pressed={active === i} aria-controls="integration-workflow" onClick={() => setActive(i)} className={`inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-xs transition focus-visible:outline-2 focus-visible:outline-offset-2 ${active === i ? 'border-white bg-white text-black' : 'border-white/30 text-white/80 hover:border-white'}`}><item.icon size={14} />{item.label}</button>)}</div></Reveal>
    <motion.div id="integration-workflow" role="region" aria-label={example.label} key={active} initial={false} animate={reduced ? undefined : { opacity: [0.4, 1], y: [8, 0] }} transition={{ duration: 0.4 }} className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:gap-20"><div><h3 className="whitespace-pre-line text-3xl font-medium leading-tight tracking-[-0.035em]">{example.title}</h3><p className="mt-5 max-w-[43ch] text-sm leading-7 text-white/65">{example.text}</p><ol className="mt-8 space-y-4">{example.steps.map((step, i) => <li key={step} className="flex items-center gap-3 text-sm text-white/85"><span className="flex size-7 shrink-0 items-center justify-center rounded-full border border-white/20 text-[9px] text-[#d0b4f2]">0{i + 1}</span>{step}</li>)}</ol></div><div className="rounded-2xl border border-[#0281f6] bg-[#edf7ff] p-3 text-[#191e19] sm:p-5"><div className="rounded-xl bg-white p-5 sm:p-7"><div className="flex items-center justify-between gap-3 border-b border-black/10 pb-4 text-xs"><span className="flex items-center gap-2"><MessageCircle size={15} /> Connected conversation</span><span className="text-[9px] text-[#81858a]">Illustrative workflow</span></div><div className="ml-auto mt-6 max-w-[90%] rounded-2xl rounded-br-sm bg-[#eee5fa] px-4 py-3 text-sm leading-6">{example.question}</div><div className="my-6 flex items-center gap-3 rounded-xl border border-[#dce8f3] bg-[#f6faff] p-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#7057a1]"><Plug size={20} /></span><div><strong className="block text-sm font-medium">{example.source}</strong><span className="mt-1 block text-[10px] text-[#628099]">{example.badge}</span></div><Check size={15} className="ml-auto shrink-0 text-[#309368]" /></div><div className="flex items-start gap-3"><Sparkles size={18} className="mt-1 shrink-0 text-[#9875c2]" /><p className="text-sm leading-7">{example.result}</p></div><div className="mt-6 flex items-center gap-2 border-t border-black/10 pt-4 text-[10px] text-[#66767c]"><example.resultIcon size={13} />{active === 0 ? 'No changes to payment records' : 'Your team takes it from here'}</div></div></div></motion.div>
  </div></section>;
}

function Access() {
  return <section className={`${wrap} py-20 sm:py-24`}><Reveal className="mb-10 grid gap-5 md:grid-cols-2 md:items-end"><div><p className="mb-4 text-xs uppercase tracking-wider text-[#7060bd]">Your connections. Your control.</p><h2 className={heading}>Useful access.<br />Clear boundaries.</h2></div><p className="max-w-[43ch] text-sm leading-7 text-[#72767d] md:ml-auto">Connect the tools your support needs, understand what each connection does, and remove access when you no longer need it.</p></Reveal><div className="grid gap-5 md:grid-cols-3">{[{ icon: LockKeyhole, title: 'Encrypted credentials', text: 'Integration credentials are encrypted at rest and used server-side for the API calls you authorize.' }, { icon: ShieldCheck, title: 'Read-only payments', text: 'Stripe and Razorpay connections provide order information for support without writing back to payment records.' }, { icon: KeyRound, title: 'Disconnect when you need', text: 'Remove a connection from your workspace. Disconnecting deletes its stored credentials.' }].map(item => <article key={item.title} className="rounded-2xl border border-black/10 p-6 sm:p-7"><item.icon size={24} className="text-[#8266ab]" /><h3 className="mt-6 text-xl font-medium tracking-[-0.025em]">{item.title}</h3><p className="mt-3 text-sm leading-7 text-[#72767d]">{item.text}</p></article>)}</div><Link href="/security-guide" className="mt-7 inline-flex items-center gap-2 text-sm underline underline-offset-4">How we protect your connections <ArrowUpRight size={15} /></Link></section>;
}

function Questions() {
  return <section className={`${wrap} pb-20`}><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:gap-16"><div><p className="text-xs uppercase tracking-wider text-[#7060bd]">FAQ</p><h2 className="mt-4 text-3xl font-medium tracking-[-0.04em] sm:text-4xl">A few connection questions.</h2><p className="mt-4 max-w-md text-sm leading-7 text-[#72767d]">A little clarity before you connect. Find more about setup, billing, and security in our FAQ.</p><Link href="/faq" className="mt-6 inline-flex items-center gap-2 text-sm font-medium underline underline-offset-4">Read the full FAQ <ArrowUpRight size={15} /></Link></div><div className="border-t border-black/10">{integrationFaqs.map(item => <details key={item.q} className="group border-b border-black/10"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-5 text-base leading-7 [&::-webkit-details-marker]:hidden">{item.q}<span className="flex size-8 shrink-0 items-center justify-center rounded-full border border-black/15 transition group-open:rotate-45 group-open:bg-[#191e19] group-open:text-white"><Plus size={16} /></span></summary><p className="pb-6 pr-4 text-sm leading-7 text-[#72767d] sm:pr-12">{item.a}</p></details>)}</div></div></section>;
}

export function IntegrationsContent() {
  return <div className="overflow-hidden bg-white font-[family-name:var(--font-rethink-sans)] text-[#191e19]"><Directory /><Workflow /><Access /><Questions /><section className={`${wrap} pb-20`}><Reveal className="grid overflow-hidden rounded-3xl bg-[#020807] text-white lg:grid-cols-[1.5fr_1fr]"><div className="bg-[radial-gradient(ellipse_at_top_left,#ddefea20,transparent_70%)] p-8 sm:p-11"><p className="text-xs uppercase tracking-wider text-[#ddefea]">Your next connection</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-tight tracking-[-0.05em] sm:text-5xl">Good tools work<br />better together.</h2><p className="mt-5 max-w-[44ch] text-sm leading-7 text-white/65">Start a workspace and connect the tools your team uses. If something is missing, tell us what would make your support easier.</p></div><div className="flex flex-col justify-center border-t border-white/10 bg-[#191c18] p-8 sm:p-9 lg:border-l lg:border-t-0"><h3 className="text-2xl font-medium tracking-tight">Make the connection.</h3><Link href="/dashboard/connect" className="mt-6 inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-[linear-gradient(120deg,#DDEFEA_0%,#EBE5FA_100%)] px-5 text-sm font-semibold text-black transition hover:brightness-105">Open your integrations <ArrowUpRight size={16} /></Link><Link href="/contact" className="mt-5 inline-flex items-center justify-center gap-2 text-sm text-white/80 underline underline-offset-4">Request an integration <ArrowRight size={14} /></Link><p className="mt-5 text-center text-xs text-white/55">New to Elpino? <Link href="/signup" className="text-white underline underline-offset-4">Start free.</Link></p></div></Reveal></section></div>;
}
