import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, ChevronRight, FileText, Search, ShieldCheck } from "lucide-react";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://elpino.chat";
export const metadata: Metadata = {
  title: "Self-Service Support",
  description: "Help customers find useful answers on their own, with self-service that stays connected to your team.",
  alternates: { canonical: `${SITE_URL}/solutions/self-service` },
};

const collections = [
  { icon: BookOpen, name: "Getting started", detail: "Setup, first steps, and account basics", articles: "12 articles" },
  { icon: FileText, name: "Using your product", detail: "Features, workflows, and best practices", articles: "28 articles" },
  { icon: ShieldCheck, name: "Account & billing", detail: "Plans, permissions, invoices, and security", articles: "16 articles" },
];

const commonTasks = [
  ["Set up an account", "Installation, access, invitations, and first-use questions."],
  ["Understand a feature", "Product behavior, workflows, limits, and best practices."],
  ["Manage a subscription", "Plans, invoices, billing details, and seat changes."],
  ["Solve a known issue", "Clear troubleshooting steps and current workarounds."],
];

export default function SelfServicePage() {
  return <main className="bg-[#fcfbfe] font-[family-name:var(--font-rethink-sans)] text-[#233d4d]">
    <section className="border-b border-[#233d4d]/15 bg-[#d9bef4] px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#69499a]">Elpino self-service</p><h1 className="mt-6 text-[clamp(3.25rem,7vw,7rem)] font-medium leading-[0.88] tracking-[-0.075em]">Help customers help themselves.</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-[#233d4d]/75">A better first stop for product questions, account tasks, and everyday support—powered by the knowledge your team approves.</p><div className="relative mx-auto mt-10 max-w-2xl rounded-2xl border border-[#233d4d]/20 bg-white p-2 shadow-[0_18px_40px_rgba(67,42,100,0.12)]"><div className="flex h-15 items-center gap-3 px-4 text-[#68717a]"><Search size={20} /><span className="flex-1 text-left text-sm sm:text-base">How can we help?</span><span className="rounded-xl bg-[#233d4d] px-4 py-2 text-xs font-semibold text-white">Search</span></div></div><p className="mt-4 text-sm text-[#233d4d]/60">Search answers, browse a topic, or ask a question in plain language.</p></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-[1100px]"><div className="flex flex-col justify-between gap-5 border-b border-[#233d4d]/15 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#7651b0]">Browse by topic</p><h2 className="mt-4 text-4xl font-medium tracking-[-0.055em] sm:text-5xl">Start with what you need.</h2></div><p className="max-w-xs text-sm leading-6 text-[#53616b]">Organize the information customers come back to again and again.</p></div><div className="mt-2 divide-y divide-[#233d4d]/15">{collections.map(({ icon: Icon, name, detail, articles }) => <Link key={name} href="/docs" className="group grid gap-4 py-6 sm:grid-cols-[52px_1fr_auto] sm:items-center"><span className="flex size-11 items-center justify-center rounded-xl bg-[#f1edf7] text-[#7651b0]"><Icon size={20} /></span><span><span className="block text-xl font-semibold tracking-[-0.03em]">{name}</span><span className="mt-1 block text-sm text-[#53616b]">{detail}</span></span><span className="flex items-center gap-4 text-sm text-[#53616b]"><span>{articles}</span><ChevronRight size={18} className="transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

    <section className="border-y border-[#233d4d]/15 bg-[#f1edf7] px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-[1100px]"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#7651b0]">The questions customers ask most</p><h2 className="mt-5 text-4xl font-medium leading-[0.95] tracking-[-0.055em] sm:text-5xl">Make common work feel effortless.</h2></div><p className="max-w-xl text-base leading-7 text-[#53616b]">Use self-service for the repeatable work that slows down customers and fills up your support queue. Keep your specialists for the questions that call for judgment.</p></div><div className="mt-10 grid gap-px overflow-hidden border border-[#233d4d]/15 bg-[#233d4d]/15 sm:grid-cols-2">{commonTasks.map(([title, detail], index) => <article key={title} className="bg-[#f1edf7] p-6 sm:p-7"><span className="font-mono text-xs text-[#7651b0]">0{index + 1}</span><h3 className="mt-8 text-xl font-semibold tracking-[-0.03em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#53616b]">{detail}</p></article>)}</div></div></section>

    <section className="border-y border-[#233d4d]/15 bg-white px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-[1100px] gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#7651b0]">Answers with substance</p><h2 className="mt-5 text-4xl font-medium leading-[0.95] tracking-[-0.055em] sm:text-6xl">More useful than a list of links.</h2><p className="mt-6 text-base leading-7 text-[#53616b]">Elpino searches the documentation, policies, and guides you have approved, then gives the customer a direct answer with the supporting source close at hand.</p><Link href="/docs" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#7651b0]">Explore the documentation <ArrowRight size={15} /></Link></div><div className="overflow-hidden rounded-2xl border border-[#233d4d]/15 bg-[#f8f7fa]"><div className="border-b border-[#233d4d]/10 bg-white px-5 py-4 text-xs font-semibold text-[#53616b]">Customer question</div><div className="p-6"><p className="text-lg font-medium leading-7">“How do I invite another teammate?”</p><div className="mt-6 rounded-xl border border-[#d8e8df] bg-[#eef7f1] p-5"><p className="text-[11px] font-bold uppercase tracking-[0.12em] text-[#28745a]">Elpino answer</p><p className="mt-3 text-sm leading-6 text-[#233d4d]">Open Settings, choose People, then select Invite teammate. You can choose a role before sending the invitation.</p><p className="mt-4 border-t border-[#28745a]/15 pt-3 text-xs text-[#28745a]">Source: Managing your team</p></div></div></div></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-[1100px] gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#7651b0]">Keep control of the answer</p><h2 className="mt-5 text-4xl font-medium leading-[0.95] tracking-[-0.055em] sm:text-5xl">Your knowledge. Your standards.</h2></div><div className="divide-y divide-[#233d4d]/15 border-y border-[#233d4d]/15"><div className="py-5"><h3 className="text-lg font-semibold">Review what the AI can use</h3><p className="mt-2 text-sm leading-6 text-[#53616b]">Choose the sources that are available to customers and remove anything that no longer reflects the product.</p></div><div className="py-5"><h3 className="text-lg font-semibold">Improve gaps as you find them</h3><p className="mt-2 text-sm leading-6 text-[#53616b]">Turn repeated questions into a stronger article, then make the updated answer available immediately.</p></div><div className="py-5"><h3 className="text-lg font-semibold">Escalate with clear boundaries</h3><p className="mt-2 text-sm leading-6 text-[#53616b]">Set the moments where self-service should step back and invite a teammate into the conversation.</p></div></div></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-[1100px] gap-10 rounded-[28px] bg-[#233d4d] p-7 text-white sm:p-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><Image src="/images/help-center-sloth.png" alt="A sloth organizing helpful customer information" width={1024} height={1536} sizes="(min-width: 1024px) 30vw, 70vw" className="mx-auto h-[280px] w-auto object-contain sm:h-[350px]" /></div><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#d9bef4]">When a person is needed</p><h2 className="mt-5 text-4xl font-medium leading-[0.95] tracking-[-0.055em] sm:text-5xl">Self-service should never be a dead end.</h2><p className="mt-6 max-w-xl text-base leading-7 text-white/65">A customer can always ask for help. When they do, your team receives the question, the conversation, and the information already checked—so nobody has to start from zero.</p><Link href="/contact" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-6 text-sm font-semibold text-[#233d4d] transition hover:bg-[#d9bef4]">Talk to our team <ArrowRight size={16} /></Link></div></div></section>
  </main>;
}
