// Integration snippets for widget identity verification, shared by the
// dashboard settings page and the public guide so the two never drift.
// Each server example must produce a token identity-token.ts accepts: HS256,
// aud "elpino-widget", a fresh jti, integer iat/exp at most five minutes
// apart, a string sub. Optional claims are omitted rather than sent as null,
// because a null email or phone is rejected as an invalid claim.

export type ServerSnippet = { id: string; label: string; install: string; code: string; lang: string };

export const SERVER_SNIPPETS: ServerSnippet[] = [
  {
    id: "node",
    label: "Node.js",
    lang: "javascript",
    install: "npm install jsonwebtoken",
    code: `// Call this from your existing authenticated page or login handler.
import jwt from "jsonwebtoken";
import { randomUUID } from "node:crypto";

function elpinoIdentityToken(user) {
  const now = Math.floor(Date.now() / 1000);
  return jwt.sign({
    sub: String(user.id),          // stable account ID, required
    aud: "elpino-widget",
    jti: randomUUID(),             // fresh for every token
    iat: now,
    exp: now + 300,                // five minutes at most
    email: user.email,             // omit this line if the user has none
    email_verified: user.emailVerified === true,
    name: user.name,               // omit this line if the user has none
  }, process.env.ELPINO_IDENTITY_SECRET, { algorithm: "HS256" });
}`,
  },
  {
    id: "python",
    label: "Python",
    lang: "python",
    install: "pip install pyjwt",
    code: `# Call this from your existing authenticated page or login handler.
import os, time, uuid
import jwt

def elpino_identity_token(user):
    now = int(time.time())
    claims = {
        "sub": str(user.id),              # stable account ID, required
        "aud": "elpino-widget",
        "jti": str(uuid.uuid4()),         # fresh for every token
        "iat": now,
        "exp": now + 300,                 # five minutes at most
        "email": user.email,              # omit this key if the user has none
        "email_verified": bool(user.email_verified),
        "name": user.name,                # omit this key if the user has none
    }
    return jwt.encode(claims, os.environ["ELPINO_IDENTITY_SECRET"], algorithm="HS256")`,
  },
  {
    id: "php",
    label: "PHP",
    lang: "php",
    install: "composer require firebase/php-jwt",
    code: `<?php
// Call this from your existing authenticated page or login handler.
use Firebase\\JWT\\JWT;

function elpino_identity_token($user): string {
    $now = time();
    $claims = [
        'sub' => (string) $user->id,           // stable account ID, required
        'aud' => 'elpino-widget',
        'jti' => bin2hex(random_bytes(16)),    // fresh for every token
        'iat' => $now,
        'exp' => $now + 300,                   // five minutes at most
        'email' => $user->email,               // omit this key if the user has none
        'email_verified' => (bool) $user->email_verified,
        'name' => $user->name,                 // omit this key if the user has none
    ];
    return JWT::encode($claims, getenv('ELPINO_IDENTITY_SECRET'), 'HS256');
}`,
  },
  {
    id: "ruby",
    label: "Ruby",
    lang: "ruby",
    install: "gem install jwt",
    code: `# Call this from your existing authenticated page or login handler.
require "jwt"
require "securerandom"

def elpino_identity_token(user)
  now = Time.now.to_i
  claims = {
    sub: user.id.to_s,                    # stable account ID, required
    aud: "elpino-widget",
    jti: SecureRandom.uuid,               # fresh for every token
    iat: now,
    exp: now + 300,                       # five minutes at most
    email: user.email,                    # omit this key if the user has none
    email_verified: user.email_verified == true,
    name: user.name                       # omit this key if the user has none
  }
  JWT.encode(claims, ENV.fetch("ELPINO_IDENTITY_SECRET"), "HS256")
end`,
  },
];

export const PAGE_SNIPPET = `<!-- Use the token from your server's page data or login response -->
<script>
  window.$elpino = window.$elpino || [];
  // elpinoToken is the signed string generated by your backend.
  $elpino.push(["identify", { token: elpinoToken }]);
</script>`;

export const SPA_SNIPPET = `// Single-page apps: tell the widget when the login state changes.
// After login, pass the fresh token included in your login response:
$elpino.push(["identify", { token: loginResponse.elpinoToken }]);

// On logout or account switch, immediately:
$elpino.push(["logout"]);`;

export const AUTO_REFRESH_SNIPPET = `// Optional: only if you want automatic token renewal.
// POST returns { token } for your logged-in user, or HTTP 401 for guests.
window.$elpino = window.$elpino || [];
$elpino.push(["configure", { identityEndpoint: "/api/chat-identity" }]);`;

// Reasons the widget logs as "[Elpino] Identity token was not accepted: <code>".
export const IDENTITY_ERRORS: Array<{ code: string; fix: string }> = [
  { code: "not_configured", fix: "Identity verification is not turned on for this workspace. Turn it on in Settings, then Identity Verification." },
  { code: "bad_signature", fix: "The token was not signed with this workspace's current secret. Check ELPINO_IDENTITY_SECRET on your server, and update it after a rotation." },
  { code: "unsupported_algorithm", fix: "Sign with HS256. Other algorithms, including none and RS256, are refused." },
  { code: "malformed", fix: "Pass the compact JWT string itself (three dot-separated parts), not a JSON object or a Bearer header." },
  { code: "invalid_audience", fix: "Set aud to exactly \"elpino-widget\"." },
  { code: "missing_expiry", fix: "Include exp as an integer Unix timestamp in seconds." },
  { code: "expired", fix: "Mint a fresh token for every request instead of caching one. Also check your server clock." },
  { code: "lifetime_too_long", fix: "exp may be at most five minutes after iat and after the current time." },
  { code: "invalid_issued_at", fix: "Include iat in seconds, not milliseconds, and keep your server clock in sync." },
  { code: "not_yet_valid", fix: "nbf is in the future. Remove it or check your server clock." },
  { code: "no_identity", fix: "Include sub, your stable account ID. An email alone is not enough." },
  { code: "invalid_claim", fix: "A claim has the wrong shape: jti must be 16 to 128 URL-safe characters, email_verified and phone_verified must be true or false, and email or phone must be omitted rather than null." },
  { code: "token_already_used", fix: "Each token works once. Generate a fresh token in your page or login response, then pass it to $elpino identify. If using an optional provider, return a new token on every call." },
];
