// Complete Tailwind class strings, shared by the product preview components.
export const productSectionStyles = {
  sections: 'overflow-hidden text-[#20231f]',
  section: 'relative bg-[#f7f6f2] px-5 py-20 sm:px-8 md:py-28 lg:px-22 [--accent:#48705a] [--tint:#e0e9df] scroll-mt-36',
  aiSection: '!bg-[#fffdf9] [--accent:#856039] [--tint:#f0dfc5]',
  cornerDots: 'pointer-events-none absolute inset-3 sm:inset-4 [&>i]:absolute [&>i]:size-1.5 [&>i]:bg-[var(--accent)] [&>i:nth-child(1)]:left-0 [&>i:nth-child(1)]:top-0 [&>i:nth-child(2)]:right-0 [&>i:nth-child(2)]:top-0 [&>i:nth-child(3)]:bottom-0 [&>i:nth-child(3)]:left-0 [&>i:nth-child(4)]:bottom-0 [&>i:nth-child(4)]:right-0',
  inner: 'mx-auto max-w-[1280px]',
  intro: 'mb-12 grid items-center gap-10 lg:mb-16 lg:grid-cols-[1.65fr_1fr] [&_h2]:text-[clamp(2.2rem,4vw,3.65rem)] [&_h2]:font-normal [&_h2]:leading-[1.08] [&_h2]:tracking-[-0.045em] [&_h2_span]:text-[#70756c]',
  eyebrow: 'mb-6 flex items-center gap-2.5 text-[11px] font-semibold tracking-[0.16em] [&>span]:size-2 [&>span]:bg-[var(--accent)]',
  description: 'mt-6 max-w-[53ch] text-base leading-7 text-[#666b61] sm:text-lg sm:leading-8',
  actions: 'mt-7 flex flex-wrap gap-3',
  primary: 'group inline-flex h-12 items-center justify-center gap-4 rounded-full bg-[#20231f] px-6 text-sm font-medium text-white transition hover:bg-[#414a3c] focus-visible:outline-2 focus-visible:outline-offset-4 [&_svg]:transition-transform hover:[&_svg]:translate-x-1',
  secondary: 'inline-flex h-12 items-center justify-center gap-4 rounded-full border border-[#c8cbc1] px-6 text-sm font-medium transition hover:bg-white focus-visible:outline-2 focus-visible:outline-offset-4 [&_svg]:transition-transform hover:[&_svg]:translate-x-1',
  illustration: 'relative mx-auto hidden size-[290px] items-center justify-center lg:flex',
  orbit: 'absolute inset-0 rounded-full border border-[var(--accent)]/20',
  orbitInner: 'absolute inset-10 rounded-full border border-dashed border-[var(--accent)]/25',
  symbol: 'flex size-32 -rotate-12 items-center justify-center rounded-[32px] border border-[var(--accent)]/25 bg-[var(--tint)] text-[var(--accent)] shadow-[12px_14px_0_0_#20231f0a]',
  satellite: 'absolute right-0 top-10 flex size-14 rotate-12 items-center justify-center rounded-2xl border border-black/10 bg-white text-[var(--accent)] shadow-lg',
  satelliteTwo: 'absolute bottom-8 left-0 flex size-14 -rotate-12 items-center justify-center rounded-2xl border border-black/10 bg-white text-[var(--accent)] shadow-lg',
  miniCheck: 'absolute bottom-5 right-10 flex size-8 items-center justify-center rounded-full bg-[var(--accent)] text-white',
  showcase: 'overflow-hidden rounded-sm border border-[#dcded4] bg-[#f7f6f2]',
  showcaseToolbar: 'flex min-h-12 items-center justify-between gap-3 border-b border-[#dcded4] px-4 text-[9px] font-medium tracking-wider sm:px-6 sm:text-[10px] [&>button]:hidden lg:[&>button]:flex [&>button]:min-h-10 [&>button]:items-center [&>button]:gap-2 [&>button]:rounded [&>button]:px-2 [&>button]:tracking-normal [&>button]:hover:bg-black/5 [&>button]:focus-visible:outline-2',
  toolbarDivider: 'mx-2 text-black/25',
  desktopShowcase: 'hidden lg:block',
  vertical: 'lg:!grid lg:grid-cols-[1.2fr_1fr] [&>div:last-child]:flex-col [&>div:last-child]:border-t-0 [&>div:last-child]:border-l',
  preview: 'min-w-0 overflow-hidden',
  featureButtons: 'flex border-t border-[#dcded4]',
  featureButton: 'relative flex min-w-0 flex-1 gap-4 overflow-hidden p-6 text-left transition-colors hover:bg-black/[0.025] focus-visible:z-10 focus-visible:outline-2 focus-visible:outline-offset-[-3px] [&_h3]:text-lg [&_h3]:font-medium [&_h3]:leading-6 [&_h3]:tracking-tight [&_p]:mt-3 [&_p]:text-sm [&_p]:leading-6 [&_p]:text-[#686d63]',
  active: 'bg-black/[0.035]',
  featureNumber: 'mt-1 text-[10px] font-medium text-[var(--accent)]',
  featureAction: 'mt-5 flex items-center gap-2 text-xs text-[var(--accent)]',
  progress: 'absolute inset-x-0 top-0 h-0.5 origin-left bg-[var(--accent)]',
  mobileShowcase: 'lg:hidden',
  accordion: 'border-b border-[#dcded4] last:border-0 [&_h3_button]:flex [&_h3_button]:w-full [&_h3_button]:items-center [&_h3_button]:gap-3 [&_h3_button]:p-5 [&_h3_button]:text-left [&_h3_button]:text-base [&_h3_button]:font-medium [&_h3_button]:focus-visible:outline-2 [&_h3_button>span]:text-xs [&_h3_button>span]:text-[var(--accent)] [&_h3_button>svg]:ml-auto [&_h3_button>svg]:shrink-0 [&_h3_button>svg]:transition-transform [&>div>p]:px-5 [&>div>p]:pb-6 [&>div>p]:text-sm [&>div>p]:leading-6 [&>div>p]:text-[#686d63]',
  deskScene: 'relative overflow-hidden bg-[#e4eadd] px-3 pb-20 pt-8 sm:px-8 sm:pt-12 lg:px-12 lg:pt-14',
  deskWindow: 'mx-auto flex min-h-[380px] max-w-[1120px] overflow-hidden rounded-xl border border-[#d2d9cc] bg-white shadow-[0_24px_70px_-25px_#36432f55] sm:min-h-[410px]',
  rail: 'hidden w-14 shrink-0 flex-col items-center gap-7 border-r border-black/5 bg-[#f6f7f3] py-4 text-[#7a8275] sm:flex [&>svg]:size-[17px]',
  railLogo: 'mb-2 flex size-8 items-center justify-center rounded-xl bg-[#344633] text-2xl font-semibold text-white',
  chatList: 'relative hidden w-[225px] shrink-0 border-r border-black/5 bg-[#fbfcf9] p-4 xl:block',
  windowHeading: 'flex items-center justify-between text-lg font-medium [&>span]:text-xs [&>span]:text-[#7a8275]',
  search: 'my-5 flex items-center gap-2 rounded-md border border-black/10 p-2 text-[10px] text-[#737b6d]',
  chatRow: 'my-1 flex gap-2 rounded-lg px-2 py-4 [&_strong]:text-[11px] [&_p]:mt-1 [&_p]:line-clamp-1 [&_p]:text-[10px] [&_p]:text-[#6a7363] [&>div]:min-w-0',
  selectedRow: 'bg-[#e8eee2]',
  avatar: 'flex size-8 shrink-0 items-center justify-center rounded-full bg-[#e7dcc8] text-[10px] font-medium text-[#665940]',
  teamOnline: 'absolute bottom-5 flex items-center gap-2 text-[10px] text-[#6a7363] [&>span]:size-1.5 [&>span]:rounded-full [&>span]:bg-[#558454]',
  conversation: 'flex min-w-0 flex-1 flex-col',
  conversationHeading: 'flex items-center gap-2 border-b border-black/5 px-3 py-4 sm:px-5 [&_strong]:block [&_strong]:text-xs [&_small]:mt-1 [&_small]:block [&_small]:text-[10px] [&_small]:text-[#747b6e]',
  status: 'ml-auto rounded-full bg-[#e7edde] px-2 py-1 text-[9px] text-[#4b6240]',
  messages: 'flex flex-1 flex-col gap-3 p-4 sm:px-6',
  timestamp: 'mb-1 text-center text-[9px] text-[#848b7f]',
  bubble: 'w-fit max-w-[88%] self-start rounded-xl rounded-tl-sm bg-[#f0f1ec] px-3 py-2.5 text-[11px] leading-[1.7] text-[#3e4737] sm:max-w-[80%] sm:text-xs',
  answer: '!self-end !rounded-tl-xl !rounded-tr-sm !bg-[#e5eddd]',
  handoffNote: 'my-1 flex items-center justify-center gap-2 text-[9px] leading-4 text-[#68745e] [&>svg]:shrink-0',
  composer: 'm-3 flex items-center justify-between gap-3 rounded-lg border border-black/10 px-3 py-3 text-[10px] text-[#7a8273]',
  contactPanel: 'hidden w-44 shrink-0 flex-col gap-4 border-l border-black/5 p-4 xl:flex [&>strong]:text-xs [&>small]:text-[10px] [&>span]:text-[10px] [&>span>strong]:mt-1 [&>span>strong]:block [&>span>strong]:font-normal [&>hr]:border-black/10',
  floatingNote: 'absolute bottom-6 left-1/2 flex w-[calc(100%-2rem)] max-w-[370px] -translate-x-1/2 items-center gap-3 rounded-xl border border-[#d9dfd0] bg-white px-4 py-3 shadow-lg sm:bottom-7 sm:left-auto sm:right-14 sm:translate-x-0 [&_strong]:block [&_strong]:text-[11px] [&_small]:mt-1 [&_small]:block [&_small]:text-[9px] [&_small]:text-[#727a6b] [&>svg]:ml-auto [&>svg]:shrink-0 [&>svg]:text-[#57824c]',
  noteIcon: 'flex size-9 shrink-0 items-center justify-center rounded-lg bg-[#e5eddd] text-[#527145]',
  aiScene: 'relative flex min-h-[490px] flex-col overflow-hidden bg-[#f1e9dc] px-5 pb-7 pt-6 sm:min-h-[570px] sm:px-9',
  sceneLabel: 'flex items-center gap-2 text-[10px] tracking-widest text-[#705c3f] [&>span]:ml-auto [&>span]:text-[9px] [&>span]:tracking-normal',
  sourceStack: 'mx-auto mt-10 flex w-full max-w-[320px] flex-col gap-3',
  source: 'flex items-center gap-3 rounded-lg border border-[#d8cfbf] bg-[#fffdf9] p-4 text-xs text-[#66583f] shadow-[0_4px_0_0_#705c3f08] [&>svg:last-child]:ml-auto [&>svg:last-child]:size-4 [&>svg:last-child]:text-[#63794f]',
  connection: 'mx-auto flex h-12 flex-col items-center justify-center gap-1 [&>span]:size-1 [&>span]:rounded-full [&>span]:bg-[#a4875b]',
  knowledgeResult: 'mx-auto w-full max-w-[350px] rounded-xl border border-[#d8cfbf] bg-[#fffdf9] p-6 text-center [&_h4]:mt-3 [&_h4]:text-xl [&_h4]:tracking-tight [&_p]:mx-auto [&_p]:mb-4 [&_p]:mt-2 [&_p]:max-w-[25ch] [&_p]:text-xs [&_p]:leading-5 [&_p]:text-[#85765f]',
  aiBadge: 'mx-auto inline-flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#e9d4b3] text-[#866237]',
  sourceTag: 'inline-flex items-center gap-2 rounded-full border border-[#d8cfbf] px-3 py-1.5 text-[9px] text-[#766347]',
  widget: 'mx-auto mt-8 flex w-full max-w-[330px] flex-1 flex-col overflow-hidden rounded-2xl border border-[#d8cfbf] bg-[#fffdf9] shadow-xl',
  widgetHeader: 'flex items-center gap-3 bg-[#342f27] p-5 text-white [&>span]:mx-0 [&_strong]:block [&_strong]:text-sm [&_small]:mt-1 [&_small]:block [&_small]:text-[10px] [&_small]:text-[#d4c9b8]',
  widgetMessages: 'flex flex-1 flex-col gap-4 p-5 [&>span]:self-end',
  audit: 'mx-auto mt-8 w-full max-w-[370px] rounded-xl border border-[#d8cfbf] bg-[#fffdf9] p-6 sm:p-8 [&>h4]:mb-7 [&>h4]:mt-4 [&>h4]:text-3xl [&>h4]:leading-tight [&>h4]:tracking-tight',
  auditEyebrow: 'text-[9px] tracking-[0.15em] text-[#92744b]',
  auditStep: 'relative flex gap-3 pb-6 last:pb-0 [&>span]:flex [&>span]:size-6 [&>span]:shrink-0 [&>span]:items-center [&>span]:justify-center [&>span]:rounded-full [&>span]:bg-[#e8eddd] [&>span]:text-[#5d7348] [&_strong]:text-xs [&_p]:mt-1 [&_p]:text-[10px] [&_p]:leading-5 [&_p]:text-[#817760]',
  sectionFoot: 'mt-6 flex flex-col justify-between gap-4 text-xs text-[#777d70] sm:flex-row sm:items-center [&>a]:flex [&>a]:items-center [&>a]:gap-2 [&>a]:text-[#444e3b] [&>a]:underline [&>a]:underline-offset-4',
} as const;
