import type { Metadata } from "next";
import { ProductFeatureLayout } from "@/app/components/product/ProductFeatureLayout";
import { Send, Sparkles, Filter, Zap, Globe, MessageSquare } from "lucide-react";

export const metadata: Metadata = {
  title: "Proactive Outbound Messaging | Elpino",
  description: "Engage visitors proactively based on URL behavior, checkout hesitation, and onboarding milestones.",
};

export default function OutboundPage() {
  return (
    <ProductFeatureLayout
      category="Outbound"
      title="Engage visitors before they"
      highlightedTitle="ever ask for help."
      description="Trigger proactive chat prompts, onboarding banners, and checkout assistance messages based on live user intent."
      features={[
        {
          title: "URL & Scroll Triggers",
          description: "Prompt visitors on pricing or checkout pages who pause for over 30 seconds with helpful tips.",
          icon: Zap,
          badge: "Proactive",
        },
        {
          title: "AI-Personalized Greetings",
          description: "Generate contextual greetings based on visitor referral source, country, or cart contents.",
          icon: Sparkles,
        },
        {
          title: "Targeted Audience Segments",
          description: "Segment messages for first-time visitors, returning users, or high-value enterprise prospects.",
          icon: Filter,
        },
        {
          title: "Announcement Banners",
          description: "Broadcast planned maintenance or new product features directly inside the live chat widget.",
          icon: MessageSquare,
        },
        {
          title: "Geolocation Routing",
          description: "Display localized language greetings based on visitor geographic IP location automatically.",
          icon: Globe,
        },
        {
          title: "Conversion Analytics",
          description: "Measure reply rates, onboarding completions, and checkout conversions generated by proactive nudges.",
          icon: Send,
        },
      ]}
      deepDiveTitle="Turn passive visitors into customers"
      deepDiveDescription="Helpful nudges that boost conversion and prevent customer drop-off."
    />
  );
}
