"use client";

import { useState, type ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Check, CheckCheck, FileText, Globe, Inbox, LockKeyhole, MessageCircle, Search, Send, ShieldCheck, Sparkles, Users } from "lucide-react";

const container = 'mx-auto max-w-[1500px] px-5 sm:px-8 lg:px-22';
const heading = 'text-[clamp(2.2rem,4.2vw,4rem)] font-semibold leading-[1.02] tracking-[-0.055em]';
const primary = 'inline-flex min-h-13 items-center justify-center gap-3 rounded-full bg-[#11120f] px-7 text-sm font-medium text-white transition hover:bg-[#34372e] focus-visible:outline-2 focus-visible:outline-offset-4';
const outline = 'inline-flex min-h-13 items-center justify-center gap-3 rounded-full border border-black/30 px-7 text-sm font-medium transition hover:bg-black/5 focus-visible:outline-2 focus-visible:outline-offset-4';

function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={false} whileInView={reduced ? undefined : { y: [20, 0], opacity: [0.45, 1] }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
}

const scenarios = [
  { label: 'AI answers', name: 'Maya Johnson', initials: 'MJ', question: 'How do I invite my teammates?', answer: 'Open Settings → Team and select Invite teammate. Enter their email to send an invitation.', source: 'Team setup guide', status: 'Answered by AI', icon: Sparkles },
  { label: 'Human handoff', name: 'Alex Lee', initials: 'AL', question: 'Can someone help me change the delivery address on my order?', answer: 'Hi Alex, happy to help! Which order would you like to update?', source: 'Handed to your team · Order change needs a person', status: 'With your team', icon: Users },
  { label: 'Customer context', name: 'Sam Kim', initials: 'SK', question: 'I need some help getting started.', answer: 'Hi Sam! Happy to help you get set up. What would you like to do first?', source: 'Customer context is available alongside the conversation', status: 'Open conversation', icon: Globe },
];

function WorkspaceDemo() {
  const [active, setActive] = useState(0);
  const reduced = useReducedMotion();
  const current = scenarios[active];
  return <div id="workspace-demo" className="scroll-mt-40">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-2" aria-label="Explore the workspace">{scenarios.map((scenario, i) => <button type="button" key={scenario.label} aria-pressed={active === i} aria-controls="feature-conversation" onClick={() => setActive(i)} className={`inline-flex min-h-10 items-center gap-2 rounded-full border px-4 text-xs transition focus-visible:outline-2 focus-visible:outline-offset-2 ${active === i ? 'border-black bg-black text-white' : 'border-black/15 bg-white hover:border-black'}`}><scenario.icon size={13} />{scenario.label}</button>)}</div><span className="text-[10px] text-[#73776e]">Interactive product preview</span></div>
    <div className="overflow-hidden rounded-t-[18px] border border-[#0281f6] bg-[#edf7ff] p-3 pb-0 sm:p-5 sm:pb-0">
      <div className="grid overflow-hidden rounded-t-xl border border-black/10 bg-white lg:grid-cols-[235px_1fr]">
        <aside className="hidden flex-col border-r border-black/10 bg-[#fafbf9] lg:flex"><div className="flex items-center gap-2 px-5 py-6 text-sm font-semibold"><Inbox size={17} /> Inbox <span className="ml-auto text-xs font-normal text-[#71786b]">3</span></div><div className="mx-4 mb-4 flex items-center gap-2 rounded-lg border border-black/10 px-3 py-2 text-[10px] text-[#7b8275]"><Search size={12} /> Find a conversation</div>{scenarios.map((item, i) => <button key={item.name} type="button" aria-pressed={active === i} aria-controls="feature-conversation" onClick={() => setActive(i)} className={`mx-2 mb-1 flex items-center gap-3 rounded-lg p-3 text-left transition ${i === active ? 'bg-[#eee6f8]' : 'hover:bg-black/5'}`}><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-[#e1d9ed] text-[10px]">{item.initials}</span><span><strong className="block text-[11px] font-medium">{item.name}</strong><span className="mt-1 block text-[9px] text-[#76806c]">{item.label}</span></span></button>)}<p className="mt-auto flex items-center gap-2 px-5 py-6 text-[10px] text-[#73776e]"><Users size={12} /> AI and your team, together.</p></aside>
        <div id="feature-conversation" role="region" aria-label={current.label} className="min-w-0"><div className="flex items-center justify-between gap-3 border-b border-black/10 px-5 py-5"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-[#eadff4] text-[10px]">{current.initials}</span><div><p className="text-sm font-medium">{current.name}</p><p className="mt-0.5 text-[10px] text-[#73776e]">Website conversation</p></div></div><span className="rounded-full bg-[#edf5e9] px-3 py-1 text-[9px] text-[#4c7241]">{current.status}</span></div>
          <motion.div key={active} initial={false} animate={reduced ? undefined : { opacity: [0.25, 1], y: [8, 0] }} transition={{ duration: 0.35 }} className="flex min-h-[275px] flex-col gap-5 px-5 py-6 sm:px-8"><p className="text-center text-[10px] text-[#8a8f83]">Example conversation · Today</p><div className="max-w-[85%] rounded-2xl rounded-tl-sm bg-[#f2f3f0] px-4 py-3 text-sm leading-6">{current.question}</div><p className="flex items-center justify-center gap-2 text-[10px] leading-5 text-[#806698]"><current.icon size={13} className="shrink-0" />{current.source}</p><div className="ml-auto max-w-[85%] rounded-2xl rounded-br-sm bg-[#eee5fa] px-4 py-3 text-sm leading-6">{current.answer}</div>{active === 2 && <div className="flex flex-wrap justify-end gap-2 text-[10px] text-[#5e6c75]"><span className="rounded border border-[#c9dfef] bg-[#edf7ff] px-3 py-1.5">London, UK</span><span className="rounded border border-[#c9dfef] bg-[#edf7ff] px-3 py-1.5">Desktop · Chrome</span><span className="rounded border border-[#c9dfef] bg-[#edf7ff] px-3 py-1.5">Page: /getting-started</span></div>}</motion.div>
          <div className="mx-5 mb-5 flex items-center justify-between rounded-xl border border-black/10 px-4 py-3 text-xs text-[#878c80]">Write a reply…<Send size={15} /></div>
        </div>
      </div>
    </div>
  </div>;
}

const capabilities = [
  { id: 'ai-answers', label: 'AI ANSWERS', title: 'Your knowledge.\nTheir next step.', text: 'Elpino searches your help articles, website pages, and documents before it answers. Your content gives each reply its starting point.', icon: Sparkles, rows: ['Search your knowledge', 'Find relevant information', 'Answer the customer'] },
  { id: 'shared-inbox', label: 'SHARED INBOX', title: 'Every conversation.\nOne place to help.', text: 'Keep your team in the same workspace. Pick up customer conversations, reply with context, and mark issues resolved.', icon: Inbox, rows: ['Customer conversations', 'Team replies and context', 'Resolved conversations'] },
  { id: 'human-handoff', label: 'HUMAN HANDOFF', title: 'AI knows when\nto bring you in.', text: 'When a question needs a person, your team gets the conversation and the reason for the handoff. No AI resolution charge for the escalation.', icon: Users, rows: ['A question needs a person', 'Context passes to your team', 'A teammate takes over'] },
  { id: 'knowledge-base', label: 'KNOWLEDGE BASE', title: 'What you know,\nready to work.', text: 'Bring website pages, help articles, and uploaded documents together into the knowledge base your agent uses to help customers.', icon: BookOpen, rows: ['Website pages', 'Help center articles', 'Uploaded documents'] },
  { id: 'audit-trail', label: 'ANSWER AUDIT TRAIL', title: 'See the thinking\nbehind the answer.', text: 'Follow what the AI checked before it replied. The conversation keeps a record your team can review when a customer needs more help.', icon: FileText, rows: ['Question received', 'Knowledge checked', 'Answer recorded'] },
  { id: 'customer-context', label: 'CUSTOMER CONTEXT', title: 'More context.\nA more helpful reply.', text: 'Keep visitor location, device information, and conversation details close at hand, so your team knows who they are helping.', icon: Globe, rows: ['Location and device', 'Current website page', 'Conversation history'] },
];

function FeatureGrid() {
  return <section id="all-features" className="scroll-mt-36 bg-black py-20 text-white sm:py-24"><div className={container}><Reveal className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-5 text-xs font-medium uppercase tracking-wider text-[#c8a5f1]">The complete workspace</p><h2 className={`${heading} uppercase`}>Built to answer.<br />Designed to help.</h2></div><p className="max-w-[34ch] text-sm leading-7 text-white/65">Everything your AI and your people need to keep customer conversations moving.</p></Reveal><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{capabilities.map((feature, i) => <Reveal key={feature.id} className="h-full"><article id={feature.id} className="flex h-full scroll-mt-36 flex-col overflow-hidden rounded-lg border-3 border-white bg-white text-[#171e16]"><div className="p-6 sm:p-7"><div className="flex items-center justify-between"><p className="text-[11px] font-medium">{feature.label}</p><feature.icon size={19} className="text-[#7d5eac]" /></div><h3 className="mt-5 whitespace-pre-line text-[28px] font-semibold leading-[1.07] tracking-[-0.04em]">{feature.title}</h3><p className="mt-5 text-sm leading-6 text-[#626a5c]">{feature.text}</p></div><div className="mx-6 mt-auto rounded-t-2xl border border-b-0 border-[#0281f6] bg-[#edf7ff] p-3 pb-0 sm:mx-7"><div className="rounded-t-lg bg-white p-4"><div className="mb-4 flex items-center justify-between text-[10px]"><span>{feature.label.toLowerCase()}</span><span className="text-[#7c8772]">Preview</span></div>{feature.rows.map((row, index) => <div key={row} className="flex items-center gap-2 border-t border-black/5 py-3 text-[11px]"><span className={`flex size-5 shrink-0 items-center justify-center rounded-full text-[9px] ${index === 2 ? 'bg-[#e4f2eb] text-[#387c59]' : 'bg-[#eee5fa] text-[#8663ac]'}`}>{i === 3 ? <FileText size={10} /> : index === 2 ? <Check size={10} /> : index + 1}</span>{row}<CheckCheck size={12} className="ml-auto shrink-0 text-[#599c7c]" /></div>)}</div></div></article></Reveal>)}</div></div></section>;
}

function KnowledgeSection() {
  return <section className="bg-[#fff1e3] py-20 sm:py-24"><div className={`${container} grid items-center gap-12 lg:grid-cols-2 lg:gap-20`}><Reveal><p className="mb-5 text-xs font-medium uppercase tracking-wider text-[#956840]">From setup to support</p><h2 className={heading}>Start with what<br />you already know.</h2><p className="mt-6 max-w-[40ch] text-base leading-7 text-[#76634f]">Your product guides and policies already hold useful answers. Give Elpino that knowledge, add your chat widget, and let the conversation begin.</p><ol className="mt-8 space-y-5">{[['Add your knowledge', 'Bring pages, documents, and help articles.'], ['Connect your website', 'Give customers a place to ask for help.'], ['Bring in your team', 'Keep people close for the questions that need them.']].map(([name, text], i) => <li key={name} className="flex items-start gap-4"><span className="flex size-8 shrink-0 items-center justify-center rounded-full border border-[#d7bda6] text-[10px]">0{i + 1}</span><div><h3 className="text-sm font-medium">{name}</h3><p className="mt-1 text-xs leading-6 text-[#826c56]">{text}</p></div></li>)}</ol><Link href="/signup" className={`${primary} mt-8`}>Set up your workspace <ArrowRight size={16} /></Link></Reveal><Reveal className="relative min-w-0 rounded-[22px] border border-[#0281f6] bg-[#edf7ff] p-5 sm:p-8"><div className="rounded-xl border border-black/5 bg-white p-5 sm:p-7"><div className="mb-6 flex items-center gap-2 text-sm font-medium"><BookOpen size={17} />Your knowledge library</div>{['Getting started guide', 'Billing and plans', 'Team setup', 'Product FAQs'].map((name, i) => <div key={name} className="flex items-center gap-3 border-t border-black/10 py-4"><FileText size={18} className="shrink-0 text-[#8d65b7]" /><div><p className="text-xs font-medium">{name}</p><p className="mt-1 text-[10px] text-[#82877a]">{i % 2 ? 'Help article' : 'Website page'}</p></div><span className="ml-auto flex items-center gap-1 text-[9px] text-[#377755]"><Check size={11} /> Ready</span></div>)}<div className="mt-5 flex items-center gap-2 rounded-lg bg-[#f0e8fa] p-3 text-[11px] text-[#79618f]"><Sparkles size={14} /> Helpful content. A helpful starting point.</div></div><div className="mt-5 flex items-center justify-between gap-4"><p className="max-w-[20ch] text-xs leading-6 text-[#54748c]">Your knowledge,<br />ready for its next question.</p><Image src="/desk_avatar1.png" width={600} height={377} alt="" sizes="160px" className="h-auto w-32 sm:w-40" /></div></Reveal></div></section>;
}

function TrustSection() {
  const details = [
    { icon: ShieldCheck, title: 'Read-only payment lookups', text: 'Connect Stripe or Razorpay so Elpino can check order information before answering a billing question.', href: '/integrations', link: 'Explore integrations' },
    { icon: LockKeyhole, title: 'Secure one-time requests', text: 'Collect sensitive customer information through a secure request, with access designed for a single viewing.', href: '/security-guide', link: 'Read the security guide' },
    { icon: FileText, title: 'An answer trail you can review', text: 'See what the AI checked and keep the context close when a teammate needs to take over.', href: '/trust', link: 'Explore trust & controls' },
  ];
  return <section className={`${container} py-20 sm:py-24`}><Reveal className="mb-12 grid gap-6 md:grid-cols-2 md:items-end"><div><p className="mb-5 text-xs uppercase tracking-wider text-[#7d648f]">Helpful comes with responsible</p><h2 className={heading}>The right information.<br />The right controls.</h2></div><p className="max-w-[39ch] text-sm leading-7 text-[#67705f] md:ml-auto">Give your team useful context and a clear record of how the AI helped.</p></Reveal><div className="grid gap-6 md:grid-cols-3">{details.map(item => <article key={item.title} className="flex flex-col border-t-2 border-black pt-6"><item.icon size={25} className="text-[#8261a6]" /><h3 className="mt-6 text-xl font-medium tracking-tight">{item.title}</h3><p className="mb-6 mt-4 text-sm leading-7 text-[#67705f]">{item.text}</p><Link href={item.href} className="mt-auto inline-flex items-center gap-2 text-xs underline underline-offset-4">{item.link}<ArrowUpRight size={14} /></Link></article>)}</div></section>;
}

export function FeaturesContent() {
  return <div className="overflow-hidden bg-white font-[family-name:var(--font-rethink-sans)] text-[#11120f]">
    <section className="relative bg-white pt-12 sm:pt-16"><div aria-hidden="true" className="pointer-events-none absolute inset-0 bg-[linear-gradient(100deg,rgba(255,255,255,0.97)_25%,rgba(255,255,255,0.78)_100%),url('/images/heros/elpino-dawn-hero.webp')] bg-cover bg-center" /><div className={`relative ${container}`}><Reveal className="mb-12 grid gap-8 lg:grid-cols-[1.35fr_1fr] lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#c5b0e5] bg-white px-3 py-1.5 text-[11px]"><Sparkles size={12} className="text-[#9a72c6]" /> The Elpino toolkit</span><h1 className="mt-7 text-[clamp(2.7rem,5.1vw,5.3rem)] font-normal leading-[1.02] tracking-[-0.055em]">Everything you need.<br /><span className="text-[#71736b]">For every next question.</span></h1></div><div><p className="max-w-[39ch] text-base leading-7 text-[#60665a] sm:text-lg sm:leading-8">AI answers, shared conversations, and your team, all working together. Explore the features that make support feel simpler.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/signup" className={primary}>Start free <ArrowRight size={16} /></Link><Link href="#all-features" className={outline}>Explore features <ArrowDown size={15} /></Link></div><p className="mt-4 text-xs text-[#72766b]">50 AI resolutions a month. No card required.</p></div></Reveal><WorkspaceDemo /></div></section>
    <nav aria-label="Feature sections" className="border-y border-black/10 bg-white"><div className={`${container} flex flex-wrap justify-center gap-x-7 gap-y-1 py-4 text-xs`}>{[['AI answers', '#ai-answers'], ['Shared inbox', '#shared-inbox'], ['Human handoff', '#human-handoff'], ['Knowledge base', '#knowledge-base'], ['Audit trail', '#audit-trail'], ['Customer context', '#customer-context']].map(([label, href]) => <Link key={href} href={href} className="py-2 text-[#5d6555] transition hover:text-[#0281f6]">{label}</Link>)}</div></nav>
    <FeatureGrid /><KnowledgeSection /><TrustSection />
    <section className="bg-[#edf7ff] py-16 sm:py-20"><Reveal className={`${container} flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center`}><div><p className="mb-4 text-xs font-medium uppercase tracking-wider text-[#527b97]">Your next helpful answer starts here</p><h2 className="text-4xl font-medium leading-[1.08] tracking-[-0.045em] sm:text-5xl">A little less busywork.<br />A lot more helping.</h2><p className="mt-5 text-sm text-[#627b8d]">Start free. Add your team as you grow.</p></div><div className="flex flex-wrap gap-3"><Link href="/signup" className={primary}>Get started <ArrowRight size={16} /></Link><Link href="/pricing" className={outline}>See pricing <ArrowUpRight size={16} /></Link></div></Reveal></section>
  </div>;
}
